using System;
using System.Collections.Generic;

namespace FrotiX.TextNormalization
    {
    /// <summary>
    /// Siglas brasileiras e internacionais comuns (fallback offline).
    /// Mantemos TODAS em maiúsculas por padrío.
    /// </summary>
    internal static class BrAcronymsSeed
        {
        public static IReadOnlyCollection<string> Values => _values.Value;

        private static readonly Lazy<IReadOnlyCollection<string>> _values = new(
            Build,
            isThreadSafe: true
        );

        private static IReadOnlyCollection<string> Build()
            {
            var set = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                // Internacionais (ONU etc.)
                "ONU",
                "OTAN",
                "OMC",
                "OMS",
                "OEA",
                "OCDE",
                "OIT",
                "OPEP",
                "UE",
                "UEFA",
                "FIFA",
                "UNESCO",
                "UNICEF",
                "UNHCR",
                "NATO",
                "WHO",
                "WTO",
                "IMF",
                "OAS",
                "OECD",
                "ILO",
                "OPEC",
                "EU",
                "NATO",
                "IAEA",
                // Brasil – governo/tributos/identificação
                "IBGE",
                "INSS",
                "SUS",
                "CPF",
                "CNPJ",
                "RG",
                "CEP",
                "CNH",
                "PIS",
                "PASEP",
                "FGTS",
                "IPVA",
                "ICMS",
                "ISS",
                "IOF",
                "IRPF",
                "IRPJ",
                "SIAFI",
                "SISBACEN",
                "SEFAZ",
                "SICAF",
                "SUSAF",
                "SICONV",
                "SICAP",
                // Órgãos e agências
                "BACEN",
                "CMN",
                "CVM",
                "BNDES",
                "CADE",
                "CGU",
                "AGU",
                "STF",
                "STJ",
                "STM",
                "TST",
                "TSE",
                "TRE",
                "TRF",
                "TJ",
                "MPF",
                "MPT",
                "MP",
                "OAB",
                "ANEEL",
                "ANATEL",
                "ANVISA",
                "ANS",
                "ANTT",
                "ANA",
                "ANTICOR",
                "IBAMA",
                "ICMBIO",
                "FUNAI",
                "FUNASA",
                "DNIT",
                "DETRAN",
                "DER",
                "INMETRO",
                "INCRA",
                "EMBRAPA",
                // Educação/Ciência
                "CAPES",
                "CNPQ",
                "MEC",
                "INEP",
                "ENEM",
                "PROUNI",
                "FIES",
                "UFBA",
                "UFPE",
                "UFRJ",
                "UFRGS",
                "UFMG",
                "UFSC",
                "UFPR",
                "UFPA",
                "UFRN",
                "UFCE",
                "USP",
                "UNICAMP",
                "UNESP",
                "UNB",
                "UERJ",
                "UEM",
                "UEFS",
                // Empresas/estatais/infra
                "PETROBRAS",
                "ELETROBRAS",
                "CORREIOS",
                "SABESP",
                "COPEL",
                "COPEL",
                "CELESC",
                "CEMIG",
                "CPFL",
                // Justiça e segurança
                "PM",
                "PC",
                "PF",
                "PRF",
                "GCM",
                "BOPE",
                "PMERJ",
                "PMESP",
                "PMMG",
                // Saúde e social
                "UBS",
                "UPA",
                "SAMU",
                "CAPS",
                "CRAS",
                "CREAS",
                "CNES",
                "SADT",
                // Economia/finanças
                "IOF",
                "FGTS",
                "PASEP",
                "SELIC",
                "CDI",
                "IPCA",
                "IGP-M",
                "IGPM",
                "INPC",
                // Tecnologia e padrões
                "HTTPS",
                "HTTP",
                "URL",
                "API",
                "CPU",
                "GPU",
                "RAM",
                "SSD",
                "HD",
                "USB",
                "NFC",
                "GPS",
                "LTE",
                "5G",
                "WiFi",
                "WIFI",
                "LAN",
                "WAN",
                "XML",
                "JSON",
                "CSV",
                "PDF",
                "SQL",
                "HTTP/2",
                "HTTP/3",
                // Outros recorrentes
                "DDI",
                "DDD",
                "CNPJMEI",
                "MEI",
                "ME",
                "EPP",
                "S/A",
                "SA",
                "LTDA",
                "EIRELI",
                "SENAI",
                "SESI",
                "SENAC",
                "SESC",
            };

            return new List<string>(set);
            }
        }
    }


